### PR TITLE
ignore tun0 for more accurate speed.

### PR DESCRIPTION
**Pull request by nagae-memooff**
tun0 is a virtual network interface add by shadowsocks. ignore  tun0 will make the speed more accurately when the shadowsocks is running.
read more about tun0:  https://github.com/chiehmin/Xposed-NetworkSpeedIndicator/issues/86

### CODE REVIEW

**Comment by ADTC** [comment]
Have you tested?

**Comment by nagae-memooff** [comment]
Already tested on my sony xperia Z1 compact, works correctly.

**Comment by ADTC** [comment]
Okay good. Why is the code indented with two spaces though? Could you indent properly with Tab characters aligning with the rest of the code?

**Comment by ADTC** [comment]
Also, please close `br2` in the `finally` block. We don't want resource leaks :smile:

**Comment by nagae-memooff** [comment]
oh,I'm so sorry!
I am not an android/java developer, so I just write this code in my vim(customized for ruby, so it will replace tab to two spaces), not in eclipse or android studio.
I 'll fix it and create a new pull request. please close this.

**Comment by nagae-memooff** [comment]
bad indent character and leaky br2 are already fixed.

**Comment by nagae-memooff** [comment]
The` tun0` seems doesn't need to be closed.

**Comment by ADTC** [comment]
Another PR is not necessary. You can simply add more commits to the branch you created the PR from. But on that note, it's bad practice to create a PR from the master branch. You should create a separate branch for the PR (next time).

I will merge this. Thanks.

**Pull request merged**
