### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by liu-yun**

### CODE REVIEW

**Comment by ADTC** [comment]
Can't read Chinese but doesn't look much different. I'll trust you on this :)

**Comment by chiehmin** [comment]
我看起來一樣阿@@，你有改哪個地方嗎？(It looks like the file is unchanged....)

**Comment by ADTC** [comment]
Oh, should I revert this? Let me know. I didn't know you still around to review... :laughing:

**Comment by chiehmin** [comment]
Sorry for being lazy for a long time >"<.....Let's wait for liu-yun's reply. Maybe there is some tiny changes in simplified Chinese that I can not tell @@

**Comment by ADTC** [comment]
@chiehmin For your convenience, here is the Beyond Compare comparison (**click on it for bigger preview**):

2015-02-25 21_58_13-print preview

**Comment by chiehmin** [comment]
Then, they are typos in the original file XD

**Comment by ADTC** [comment]
Great then. Closed :)

**Pull request merged**
